"use client";

/**
 * Developer diagnostic view: renders drift audits generated by
 * analytics-engine-py/src/diagnostics.py, flagging parameter anomalies and
 * system adjustment recommendations.
 */
export default function DiagnosticsLog({ entries }) {
  return (
    <section
      style={{
        border: "1px solid #21262d",
        borderRadius: "8px",
        padding: "16px",
        backgroundColor: "#0d141f",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          marginBottom: "12px",
        }}
      >
        <h2 style={{ margin: 0, fontSize: "16px" }}>DIAGNOSTICS — AI SELF-CORRECTION</h2>
        <span style={{ fontSize: "12px", color: "#8b949e" }}>
          {entries.length} audit record(s)
        </span>
      </div>

      {entries.length === 0 ? (
        <p style={{ color: "#8b949e", fontSize: "13px" }}>
          No LOST-bet drift audits in this session.
        </p>
      ) : (
        <ul style={{ listStyle: "none", margin: 0, padding: 0 }}>
          {entries.map((entry, idx) => (
            <li
              key={`${entry.match_id}-${idx}`}
              style={{
                border: "1px solid #21262d",
                borderRadius: "6px",
                padding: "10px",
                marginBottom: "10px",
                backgroundColor: "#161b22",
              }}
            >
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <strong style={{ fontSize: "13px" }}>{entry.match_id}</strong>
                <span
                  style={{
                    fontSize: "12px",
                    color: "#f85149",
                    fontWeight: "bold",
                  }}
                >
                  drift {entry.drift_score}
                </span>
              </div>
              <p style={{ margin: "6px 0", fontSize: "12px", color: "#8b949e" }}>
                final {entry.final_home}–{entry.final_away} · predicted{" "}
                {entry.predicted_side}
              </p>
              <ul style={{ margin: "4px 0 0", paddingLeft: "18px" }}>
                {(entry.recommendations || []).map((rec, i) => (
                  <li key={i} style={{ fontSize: "12px", color: "#d29922" }}>
                    {rec}
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}